### ISSUE TITLE
AMTcgiloc is not defined

### ISSUE THREAD

**Issue by icjking** [tylingsoft/markdown-core#3]
AMTcgiloc is not defined ? why?

**Comment by tylerlong** [comment]
I've made lots of changes recently and I haven't  released it to npm yet. Please wait for updates.

It is helpful if you can share with me some information about how you are using markdown-core. Sample code is preferred. In another word, you need to tell me how to reproduce the problem.

**Comment by tylerlong** [comment]
Try the latest version

```
yarn install
yarn build
host and open dist/index.html
```
