### ISSUE TITLE
running provided example nothing happens, get errors

### ISSUE THREAD

**Issue by nerminba** [tylingsoft/markdown-core#4]
When I upload provided example to my host and run it, first I get an error in console about

index.bundle.js not being loaded since it can't be found. This file is refered to in index.html
<script src="index.bundle.js"></script>
When I comment this out, no errors are produced anymore, but also nothing happens, emtpy page.

I tried adding this code:

var mdc = require('markdown-core/markdown-core-node');
var markdown = '# your markdown here';
var html = mdc.render(markdown);
$('.markdown-body').html(html);

and I get
Uncaught ReferenceError: require is not defined

How can I test the provided example?

**Comment by tylerlong** [comment]
If your app is for web instead of node.js, you need to compile the project first:

```
yarn build
```

Command above will generate `index.bundle.js` file.

**Comment by tylerlong** [comment]
```
yarn install
yarn build
host and open dist/index.html
```
